#!/bin/bash 


#run time (hh:mm:ss)
#PBS -l walltime=00:01:00 
#1 node, 1 core per node
#PBS -l nodes=1:ppn=1     
#queue name normal|debug
#PBS -q batch            

# job name
#PBS -N cuda-hello        

#working directory for job
#join stdin/stderr
#PBS -j oe                 

#put logfiles here
#PBS -o $HOME/logs/

#echo commands before execution; use for debugging
#set -x           

date
qstat -f $PBS_JOBID

BINHOME=$HOME/xsede-demos/build

$BINHOME/cuda-hello

date
