#!/bin/bash 

#run time (hh:mm:ss)
#PBS -l walltime=00:02:00 
#1 node, 1 core per node
#       (you are always charged for the entire node)
#PBS -l nodes=4:ppn=1     

#queue name 
#PBS -q batch              

# job name
#PBS -N cuda-mpi       

#join stdin/stderr
#PBS -j oe                 
#put logfiles here
#PBS -o $HOME/logs/

#echo commands before execution; use for debugging
set -x           


qstat -f $PBS_JOBID

BINHOME=$HOME/xsede-demos/build

#get number of processors from nodefile
NP=`wc -l ${PBS_NODEFILE} | cut -d'/' -f1`

MPIRUN=""

if which mpirun | grep -q openmpi 
then
  echo "Using OpenMPI"
  #if using openmpi, we can dump the standard output of each process
  #to a separate file
  MPIRUN="mpirun --output-filename $HOME/logs/$PBS_JOBNAME.o${PBS_JOBID}log"
else
  echo "Using MVAPICH2"
  MPIRUN="mpirun_rsh -ssh"
fi

${MPIRUN} -np ${NP} -hostfile ${PBS_NODEFILE} $BINHOME/cuda-mpi 8

