#!/bin/bash

# adapted from http://www.tacc.utexas.edu/user-services/user-guides/stampede-user-guide#appdev
# see also /share/doc/sge on Stampede

#SBATCH -J	cuda-mpi	#JobName
#SBATCH -o CUDAMPI.o%j            # Name of the output file
#SBATCH -n 4			#Number of processes
#BATCH -N 4 			#Number of nodes           
#SBATCH -p gpudev          # Queue name "normal|long|largemem|development"
#SBATCH --mail-type=begin       #Send Mail at Beginning and End
#SBATCH --mail-type=end  
#SBATCH -t 00:00:45        # Run time (hh:mm:ss)
set -x                     # Echo commands, use "set echo" with csh

#set the path to the executables
export BINHOME=$HOME/xsede-demos/build
LOGOPT=""

ibrun $LOGOPT $BINHOME/cuda-mpi 8
mv CUDAMPI.o$SLURM_JOB_ID $HOME/logs

