#!/bin/bash
# adapted from http://www.tacc.utexas.edu/user-services/user-guides/longhorn-user-guide#appdev

#SBATCH -p normal          # Queue(partition)
#SBATCH -t 00:01:00                # runtime              
#SBATCH -J mpi-hello		#Job Name
#SBATCH -o myMPI.o%j  # Name of the output file (eg. myMPI.oJobID) 
#SBATCH --mail-type=begin	#Send Mail at Beginning and End
#SBATCH --mail-type=end		
#SBATCH -n 8
#SBATCH -N 1

#set the path to the executables
export BINHOME=$HOME/xsede-demos/build
#run app 

ibrun $BINHOME/mpi-hello       
mv myMPI.o$SLURM_JOB_ID $HOME/logs

