#!/bin/bash

# adapted from http://www.tacc.utexas.edu/user-services/user-guides/longhorn-user-guide#appdev
# see also /share/doc/sge on longhorn

#SBATCH -J cuda-hello           # Job Name
#SBATCH -o output.out   # Name of the output file
#SBATCH -p gpudev                # Queue Name
#SBATCH -t  00:00:15            # Run time (hh:mm:ss)
#SBATCH --mail-type=begin       #Send Mail at Beginning and End
#SBATCH --mail-type=end     
#SBATCH	-n 1
set -x                     # Echo commands, use "set echo" with csh

#set the path to the executables
export BINHOME=$HOME/xsede-demos/build
$BINHOME/cuda-hello        # Run the single thread cuda app "cuda-hello"

