#!/bin/bash

# adapted from http://www.tacc.utexas.edu/user-services/user-guides/longhorn-user-guide#appdev
# see also /share/doc/sge on longhorn

#SBATCH -J	cuda-mpi	#JobName
#SBATCH -o output2.out            # Name of the output file
#SBATCH -n 8 			           
#SBATCH -p gpudev          # Queue name "normal|long|largemem|development"
#SBATCH --mail-type=begin       #Send Mail at Beginning and End
#SBATCH --mail-type=end  
#SBATCH -t 00:00:45        # Run time (hh:mm:ss)
set -x                     # Echo commands, use "set echo" with csh

#set the path to the executables
export BINHOME=$HOME/xsede-demos/build
LOGOPT=""

#if using openmpi, we can dump the standard output of each process
#to a separate file
if which mpirun | grep -q openmpi 
then
  LOGOPT="--output-filename $HOME/logs/$JOB_NAME.o${JOB_ID}log"
fi

ibrun $LOGOPT $BINHOME/cuda-mpi 8
