#!/bin/bash 

#inherit submission environment
#PBS -V                   

#run time (hh:mm:ss)
#PBS -l walltime=00:01:00 
#1 node, 1 core per node
#       (you are always charged for the entire node)
#PBS -l nodes=1:ppn=1     
#queue name normal|debug
#PBS -q normal              

# job name
#PBS -N cuda-hello        

#working directory for job
#join stdin/stderr
#PBS -j oe                 

#put logfiles here
#PBS -o $HOME/logs/

#echo commands before execution; use for debugging
set -x           

# Go to the job scratch directory. Use cdjob <jobid> to go to this
# directory once the job has started.
cd $SCR

BINHOME=$HOME/tg-demos/build
# Copy executable file to the job scratch directory ($SCR)
# (Use msscmd to get your files if they are in NCSA MSS)
cp $BINHOME/cuda-hello .
./cuda-hello

