#!/bin/bash

# adapted from http://www.tacc.utexas.edu/user-services/user-guides/longhorn-user-guide#appdev
# see also /share/doc/sge on longhorn

#$ -V                      # Inherit the submission environment
#$ -cwd                    # Start job in submission directory
#$ -N mpihello             # Job Name
#$ -j y                    # Combine stderr and stdout

# Name of the output file (eg. myMPI.oJobID)
#$ -o $HOME/logs/$JOB_NAME.o$JOB_ID   

#$ -pe 8way 8              # 8 processes on one host
#$ -q development          # Queue name "normal|long|largemem|development"
#$ -P data                 # SGE project type (one of: vis, data, gpgpu, hpc) 
#$ -l h_rt=00:01:00        # Run time (hh:mm:ss)
set -x                     # Echo commands, use "set echo" with csh

#reduce the number of mpi jobs from the max available from -pe
export MY_NSLOTS=7

#set the path to the executables
export BINHOME=$HOME/tg-demos/build
#run app 


LOGOPT=""

#if using openmpi, we can dump the standard output of each process
#to a separate file
if which mpirun | grep -q openmpi 
then
  LOGOPT="--output-filename $HOME/logs/$JOB_NAME.o${JOB_ID}log"
fi

ibrun $LOGOPT $BINHOME/mpi-hello       

