#!/bin/bash

# adapted from http://www.tacc.utexas.edu/user-services/user-guides/longhorn-user-guide#appdev
# see also /share/doc/sge on longhorn

#$ -V                      # Inherit the submission environment
#$ -cwd                    # Start job in submission directory
#$ -N hello                # Job Name
#$ -j y                    # Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID   # Name of the output file (eg. myMPI.oJobID)
#$ -pe 1way 8              # 1 task/node, 8 nodes
#$ -q development          # Queue name "normal|long|largemem|development"
#$ -P data                 # SGE project type (one of: vis, data, gpgpu, hpc) 
#$ -M adanner@cs.swarthmore.edu #address for status messages
#$ -l h_rt=00:01:00        # Run time (hh:mm:ss)
#$ -m be                   # Email at Begin and End of job
set -x                     # Echo commands, use "set echo" with csh

#set the path to the executables
export BINHOME=$HOME/research/tg-demos/build
$BINHOME/hello             # Run the single thread executable named "hello"

